home/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from home import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
]

itmemory/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from home.views import Search

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^search', login_required(Search.as_view()), name='index'),
    url(r'^objects/', include('objects.urls', namespace="objects")),
    url(r'^ittasks/', include('ittasks.urls', namespace="ittasks")),
    url(r'^customers/', include('customers.urls', namespace="customers")),
    url(r'^hwlogs/', include('hwlogs.urls', namespace="hwlogs")),
    url(r'^hpilo/', include('hpilo.urls', namespace="hpilo")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin_tools/', include('admin_tools.urls')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns(
    'django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'login.html'}, name='mysite_login'),
    url(r'^logout/$', 'logout', {'next_page': '/'}, name='mysite_logout'),
)

home/views.py
# coding=utf-8
import calendar
from datetime import datetime, date
from django.db.models.query_utils import Q
from django.views import generic
from docutils.nodes import field_name
from ittasks.models import Task
from django.db.models.loading import get_model
from django.db import models

SEARCH_MODELS = [
    ("objects.HardwareObject", ["remote_token"], "/objects/{0}/"),
    ("customers.Customer", [], "/customers/{0}/"),
]

REPLACES = {
    "[": "<strong>",
    "]": "</strong>",
    "(": """<br><small><span class="text-muted">""",
    ")": "</span></small>",
    }


class Search(generic.TemplateView):
    template_name = "home/search.html"

    def get_context_data(self, **kwargs):
        res = list()
        search_text = self.request.GET["q"]
        if search_text == "":
            search_text = "£$%&"
        for sitem in SEARCH_MODELS:
            model = get_model(sitem[0])
            query = Q()
            for field in model._meta.fields:

                if field.name not in sitem[1] and isinstance(field, (models.CharField, models.TextField)):
                    query |= Q(**{'{0}__icontains'.format(field.name): search_text})

            search_result = model.objects.filter(query).all()
            for model_item in search_result:
                label = unicode(model_item)
                for i, j in REPLACES.iteritems():
                    label = label.replace(i, j)
                res.append({
                    "model": model._meta.verbose_name_plural,
                    "label": label,
                    "url": sitem[2].format(model_item.id)
                })
        return {"results": res}


class IndexView(generic.ListView):
    template_name = 'home/index.html'
    context_object_name = 'tasks_list'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        now = datetime.now()
        void, dayend = calendar.monthrange(now.year, now.month)
        monthstart = date(day=1, month=now.month, year=now.year)
        monthend = date(day=dayend, month=now.month, year=now.year)
        openedthismonth = Task.objects.filter(laststart__gte=monthstart, laststart__lte=monthend, done=False).count()
        closedthismonth = Task.objects.filter(laststart__gte=monthstart, laststart__lte=monthend, done=True).count()
        userdone_count = Task.objects.filter(user=self.request.user, done=True).count()
        context['openedtasks'] = Task.objects.filter(done=False).exclude(user=self.request.user).order_by("laststart")
        context['usertasks'] = Task.objects.filter(user=self.request.user, done=False).order_by("laststart")
        context['recentclosedtasks'] = Task.objects.filter(done=True).order_by("laststart")[:10]

        stats = [
            {
                'label': 'Le tue verfiche da eseguire',
                'value': str(context['usertasks'].count()),
                'icon': 'user',
                'color': 'red'
            },
            {
                'label': 'Verifiche eseguite da te',
                'value': str(userdone_count),
                'icon': 'ok',
                'color': 'green'
            },
            {
                'label': 'Verifiche nel mese',
                'value': str(openedthismonth),
                'icon': 'dashboard',
                'color': 'red'
            },
            {
                'label': 'Verifiche eseguite nel mese',
                'value': str(closedthismonth),
                'icon': 'ok',
                'color': 'green'
            },
        ]
        context['stats'] = stats
        return context

    def get_queryset(self):
        return Task.objects.all()

home/templates/base.html
{% extends 'sbadmin2/base.html' %}
{% load staticfiles %}
{% load djfrontend %}
{% load itmemory_tags %}
{% load tasks_calendar %}
{% load sbadmin_tags %}

{% block title %}Gestione assistenza tecnica{% endblock title %}
{% block body_id %}mysite_body{% endblock body_id %}
{% djfrontend_jquery %}
{% djfrontend_normalize %}
{% block custom_page_scripts %}
    {{ block.super }}
    <script src="{% static 'js/tables.js' %}" defer></script>
{% endblock %}
{%  block links %}
    <li class="{% active_page request 'home' %}"><a class="{% active_page request 'home' %}" href="/"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a></li>
    <li class="{% active_page request 'customers' %}"><a class="{% active_page request 'customers' %}" href="{% url 'customers:index'  %}">{% fa_icon 'group' %} Clienti</a></li>
    <li class="{% active_page request 'objects' %}"><a class="{% active_page request 'objects' %}" href="{% url 'objects:index'  %}">{% fa_icon 'desktop' %} Dispositivi</a></li>
    <li class="{% active_page request 'ittasks' %}"><a class="{% active_page request 'ittasks' %}" href="{% url 'ittasks:index'  %}">{% fa_icon 'tasks' %} Attivit&agrave;</a></li>
    <li class="{% active_page request 'admin' %}"><a class="{% active_page request 'admin' %}" href="{% url 'admin:index'  %}">{% fa_icon 'wrench' %} Impostazioni</a></li>
{%  endblock %}

{% block nav_bar %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!--<div class="container">-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {% block nav_bar_brand %}
            <a class="navbar-brand" href="/"><img style="max-width:180px; margin-top: -15px;" src="{% static "itmemory.png" %}"></a>
            {% endblock nav_bar_brand %}
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            </ul>
            {% block toggle_login %}
            {% include "toggle_login.html" %}
            {% endblock %}
        </div>
        <!--/.navbar-collapse -->
    <!--</div>-->
</nav>
{% endblock nav_bar %}

{% block dropdown_tasks %}
    {% personal_tasks %}
{% endblock %}

home/templates/base_popup.html
{% load staticfiles %}
{% block body_contents %}
{% endblock body_contents %}

home/templates/icon.html
<span class="glyphicon glyphicon-{{ iconname }}" aria-hidden="true"></span>

home/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Login{% endblock %}

{% block toggle_login %}{% endblock %}

{% block custom_page_scripts %}
{{ block.super }}
        <link href="{%  static 'css/login.css' %}" rel="stylesheet">

{% endblock custom_page_scripts %}

{% block body_contents %}
    <div class="col-lg-offset-4 col-lg-4 back-notransp">
        <form action="{% url 'mysite_login' %}" method="post" accept-charset="utf-8">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <input class="btn btn-info pull-right" type="submit" value="Login"/>
        </form>
    </div>
{% endblock %}

home/templates/toggle_login.html
{% if user.is_authenticated %}
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropuser">
        <li><i class="fa fa-user fa-fw"></i> {{ user.get_full_name|default:user.username }} </li>
        <li><a href="/admin/password_change/">Cambia password</a></li>
        <li><a href="{% url "mysite_logout" %}">Logout</a></li>
    </ul>
{% endif %}