home/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from home import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
]

hpilo/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from hpilo import views
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    url(r'^upload/(?P<hwid>[0-9]+)/(?P<hwtoken>[\w]+)$', csrf_exempt(views.UploadView.as_view()), name='hpiloupload'),
    url(r'^pack/(?P<hwid>[0-9]+)$', login_required(views.CreatePack.as_view()), name='createpack'),
    url(r'^chart/(?P<detailid>[0-9]+)$', login_required(views.sensorchart), name='sensorgraph'),
]

itmemory/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from home.views import Search

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^search', login_required(Search.as_view()), name='index'),
    url(r'^objects/', include('objects.urls', namespace="objects")),
    url(r'^ittasks/', include('ittasks.urls', namespace="ittasks")),
    url(r'^customers/', include('customers.urls', namespace="customers")),
    url(r'^hwlogs/', include('hwlogs.urls', namespace="hwlogs")),
    url(r'^hpilo/', include('hpilo.urls', namespace="hpilo")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin_tools/', include('admin_tools.urls')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns(
    'django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'login.html'}, name='mysite_login'),
    url(r'^logout/$', 'logout', {'next_page': '/'}, name='mysite_logout'),
)

objects/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from objects import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>[0-9]+)/pwd$', login_required(views.getpassword), name='getpassword'),
    url(r'^(?P<pk>[0-9]+)/act_task/(?P<task>[0-9]+)$', login_required(views.createtask), name='createtask'),
    url(r'^(?P<objid>[0-9]+)/addpassword$', login_required(views.PasswordCreate.as_view()), name='addpassword'),
    url(r'^(?P<objid>[0-9]+)/password/(?P<pk>[0-9]+)$', login_required(views.PasswordUpdate.as_view()),
        name='password'),
    url(r'^(?P<objid>[0-9]+)/addsetting$', login_required(views.SettingCreate.as_view()), name='addsetting'),
    url(r'^(?P<objid>[0-9]+)/setting/(?P<pk>[0-9]+)$', login_required(views.SettingUpdate.as_view()), name='setting'),
]

hwlogs/models.py
# coding=utf-8
import os
import datetime
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.db import models
from templated_email import send_templated_mail
from objects.models import HardwareObject

# Windows Event Columns
# Message,Id,Level,RecordId,ProviderName,LogName,TimeCreated


class HwLog(models.Model):
    class Meta():
        verbose_name = "Log dispositivo"
        verbose_name_plural = "Logs dispositivo"
        ordering = ['-time']

    ERROR_LEVELS = [
        ('0',	'Undefinited'),
        ('1',	'Critical'),
        ('2',	'Error'),
        ('3',	'Warning'),
        ('4',	'Informational'),
        ('5',	'Verbose'),
    ]
    ERROR_LEVELS_ICONS = {
        0:	'exclamation-sign',
        1:	'exclamation-sign',
        2:	'exclamation-sign',
        3:	'warning-sign',
        4:	'info-sign',
        5:	'info-sign',
    }

    ERROR_LEVELS_COLORS = {
        0:	'#BEBD7F',
        1:	'#FF6347',
        2:	'#FF6347',
        3:	'#7fff00',
        4:	'#BEBD7F',
        5:	'#BEBD7F',
    }

    hardwareobject = models.ForeignKey(HardwareObject, related_name="systemlogs")
    message = models.TextField("Messaggio")
    event_id = models.IntegerField("Id evento")
    level = models.CharField("Livello", max_length=10, choices=ERROR_LEVELS)
    record_id = models.IntegerField("Id record", null=True, blank=True)
    log_name = models.CharField("Nome log", max_length=255)
    time = models.DateTimeField("Ora")

    def _short_message(self):
        return self.message[:60]

    short_message = property(_short_message)

    def _level_icon(self):
        return self.ERROR_LEVELS_ICONS[int(self.level)]

    def _level_color(self):
        return self.ERROR_LEVELS_COLORS[int(self.level)]

    level_icon = property(_level_icon)
    level_color = property(_level_color)
    important = models.BooleanField("Importante", default=False)
    notify_count = models.IntegerField("Notifiche inviate", default=0)


def today():
    return datetime.datetime.now()


def add_hour(date, hour):
    return date + datetime.timedelta(days=hour)


def add_minute(date, minute):
    return date + datetime.timedelta(minutes=minute)


def add_day(date, days):
    return date + datetime.timedelta(days=days)


def add_month(date, months):
    return date + datetime.timedelta(months=months)


class LogFilter(models.Model):
    class Meta():
        verbose_name = "Filtro log"
        verbose_name_plural = "Filtri log"
        ordering = ['-name']

    name = models.CharField("Nome/Oggetto", max_length=125)
    OPERATION_CHOICE = (
        (0, "Visualizza"),
        (1, "Non importare, cancella"),
        (2, "Notifica via email"),
        (3, "Segna come importante"),
    )
    user = models.ForeignKey(User, null=True, blank=True, related_name="logfilters", verbose_name="Destinatario mail")
    group = models.ForeignKey(Group, null=True, blank=True, related_name="logfilters", verbose_name="Destinatari mail")
    operation = models.IntegerField("Operazione", choices=OPERATION_CHOICE)

    def __unicode__(self):
        return self.name

    def apply_filter(self, queryset):
        vals = self.filters.all()
        for val in vals:
            filtervalue = val.value.encode('ascii', 'ignore')
            if filtervalue.startswith("{") and filtervalue.endswith("}"):
                filtervalue = filtervalue.replace("import", "").strip("{}")
                filtervalue = eval(filtervalue)
            kwargs = {val.value_field+val.val_op: filtervalue}
            if val.exclude_value == 0:
                queryset = queryset.filter(**kwargs)
            else:
                queryset = queryset.exclude(**kwargs)
        return queryset


class LogFilterValues(models.Model):
    class Meta():
        verbose_name = "Valore di filtro"
        verbose_name_plural = "Valori di filtro"
        ordering = ['weight']

    logfilter = models.ForeignKey(LogFilter, related_name="filters", verbose_name="Filtro")

    VALUEFIELD_CHOICES = (
        ('event_id', 'Id evento'),
        ('level', 'Livello'),
        ('log_name', 'Nome log'),
        ('message', 'Messaggio'),
        ('record_id', 'Id record'),
        ('time', 'Ora')
    )
    value_field = models.CharField(max_length=255, choices=VALUEFIELD_CHOICES)

    COMPARE_OPERATIONS = (
        (0, 'uguale'),
        (1, 'contiene'),
        (2, 'maggiore di'),
        (3, 'minore di'),
        (4, 'uguale o maggiore di'),
        (5, 'uguale o minore di'),
    )

    COMPARE_OPERATIONS_SUFFIX = {
        0: '__exact',
        1: '__icontains',
        2: '__gt',
        3: '__lt',
        5: '__gte',
        6: '__lte',
    }
    operation = models.IntegerField("Confronto", choices=COMPARE_OPERATIONS)

    value = models.TextField("Valore")

    def _val_op(self):
        return self.COMPARE_OPERATIONS_SUFFIX[int(self.operation)]

    val_op = property(_val_op)

    weight = models.IntegerField("Ordine", default=1)

    INCLUDE_CHOICES = (
        (0, "Includi"),
        (1, "Escludi")
    )

    exclude_value = models.IntegerField("Escludi valori", default=0, choices=INCLUDE_CHOICES)


def logsfromfile(receivedfile):
        filedata = receivedfile.split("-")
        objid = filedata[1]
        obj = None
        if objid.isdigit():
            obj = HardwareObject.objects.get(id=objid)

        if obj:
            import csv
            with open(receivedfile, 'rb') as csvfile:
                spamreader = csv.reader(csvfile, delimiter=',', quotechar='"')
                colnames = spamreader.next()
                colindex = dict(zip(colnames, range(0, len(colnames))))
                for row in spamreader:
                    log = HwLog(hardwareobject=obj)
                    log.message = row[colindex["Message"]]
                    log.record_id = row[colindex["RecordId"]]
                    log.event_id = row[colindex["Id"]]
                    log.level = row[colindex["Level"]]
                    log.log_name = row[colindex["ProviderName"]]
                    log.time = row[colindex["TimeCreated"]].replace('.',':')
                    log.save()
        os.remove(receivedfile)
        from django.core.management import call_command
        call_command('logrotate')


def send_mail_log(logs, subject, user, template):
    if user.email is None:
        return
    return send_templated_mail(
        template_name=template,
        from_email=settings.EMAIL_SENDER,
        recipient_list=[user.email],
        context={
            'subject': subject,
            'username': user.username,
            'full_name': user.get_full_name(),
            'logs': logs
        },
    )

objects/views.py
import datetime
from django.core.urlresolvers import reverse
from django.forms import HiddenInput
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views import generic
from django.views.generic import UpdateView, CreateView
from objects.models import HardwareObject, SoftwarePassword, Settings
from ittasks.models import TaskTemplate, Task
from django.db.models import Q


class IndexView(generic.ListView):
    template_name = 'objects/index.html'
    context_object_name = 'objects_list'
    paginate_by = 15

    def post(self, request, *args, **kwargs):

        kwargs['obj_name'] = request.POST['obj_name']
        return self.get(self, request, *args, **kwargs)

    def get_queryset(self):
        items = HardwareObject.objects.all()
        if 'obj_name' in self.request.POST.keys() and self.request.POST['obj_name']:
            return items.filter(name__icontains=self.request.POST['obj_name'])
        if 'obj_serial' in self.request.POST.keys() and self.request.POST['obj_serial']:
            return items.filter(serial__icontains=self.request.POST['obj_serial'])
        if 'cust_name' in self.request.POST.keys() and self.request.POST['cust_name']:
            return items.filter(
                Q(worksite__customer__name__icontains=self.request.POST['cust_name']) |
                Q(worksite__name__icontains=self.request.POST['cust_name'])
            )
        return items


def createtask(request, pk, task):
    if request.user.is_authenticated() and request.is_ajax:
        hwobj = get_object_or_404(HardwareObject, id=pk)
        taskobj = get_object_or_404(TaskTemplate, id=task)
        newtask = Task(template=taskobj, hardwareobject=hwobj)
        newtask.laststart = datetime.datetime.now()
        newtask.laststart = newtask.nextstart
        newtask.save()
    return HttpResponseRedirect(reverse("objects:detail", kwargs={"pk": hwobj.id}))


def getpassword(request, pk):
    if request.user.is_authenticated() and request.is_ajax:
        pwd = get_object_or_404(SoftwarePassword, id=pk)
        return JsonResponse({"password": pwd.plainpassword})
    else:
        return HttpResponse("invalid data or error")


class DetailView(generic.DetailView):
    model = HardwareObject
    template_name = 'objects/detail.html'
    context_object_name = 'obj'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        from ittasks.models import Task

        context['openedtasks'] = Task.objects.filter(hardwareobject_id=context['obj'].id, done=False)
        context['closedtasks'] = Task.objects.filter(hardwareobject_id=context['obj'].id, done=True)
        return context

    def get_queryset(self):
        return HardwareObject.objects.all()


class PasswordCreate(CreateView):
    template_name = "objects/password.html"
    model = SoftwarePassword

    def get_initial(self):
        initial = {'hardwareobject': self.kwargs.get('objid')}
        if self.request.GET.get('grp'):
            initial["settingtype"] = self.request.GET.get('grp')
        return initial

    def get_success_url(self):
        return reverse("objects:detail", kwargs={"pk": self.kwargs.get('objid')})

    def get_form(self, form_class):
        form = super(PasswordCreate, self).get_form(form_class=form_class)
        # form.fields['hardwareobject'].widget.attrs['readonly'] = True
        form.fields['hardwareobject'].widget.attrs['disabled'] = True

        # import pdb
        # pdb.set_trace()
        return form


class PasswordUpdate(UpdateView):
    template_name = "objects/password.html"
    model = SoftwarePassword

    def get_initial(self):
        initial = {'hardwareobject': self.kwargs.get('objid')}
        return initial

    def get_success_url(self):
        return reverse("objects:detail", kwargs={"pk": self.kwargs.get('objid')})

    def get_form(self, form_class):
        form = super(PasswordUpdate, self).get_form(form_class=form_class)
        form.fields['hardwareobject'].widget.attrs['readonly'] = True
        form.fields['hardwareobject'].widget.attrs['disabled'] = True

        # import pdb
        # pdb.set_trace()
        return form


class SettingCreate(CreateView):
    template_name = "objects/password.html"
    model = Settings

    def get_initial(self):
        initial = {'hardwareobject': self.kwargs.get('objid')}
        if self.request.GET.get('grp'):
            initial["type"] = self.request.GET.get('grp')
        return initial

    def get_success_url(self):
        return reverse("objects:detail", kwargs={"pk": self.kwargs.get('objid')})

    def get_form(self, form_class):
        form = super(SettingCreate, self).get_form(form_class=form_class)
        form.fields['hardwareobject'].widget.attrs['readonly'] = True
        form.fields['hardwareobject'].widget.attrs['disabled'] = True
        return form


class SettingUpdate(UpdateView):
    template_name = "objects/password.html"
    model = Settings

    def get_initial(self):
        initial = {'hardwareobject': self.kwargs.get('objid')}
        return initial

    def get_success_url(self):
        return reverse("objects:detail", kwargs={"pk": self.kwargs.get('objid')})

    def get_form(self, form_class):
        form = super(SettingUpdate, self).get_form(form_class=form_class)
        form.fields['hardwareobject'].widget.attrs['readonly'] = True
        form.fields['hardwareobject'].widget.attrs['disabled'] = True

        # import pdb
        # pdb.set_trace()
        return form

objects/templates/objects/detail.html
{% extends 'objects/index.html' %}
{% load staticfiles %}
{% load objects_tags %}
{% load itmemory_tags %}
{% load sbadmin_tags %}
{% load hpilo_tags %}
{% block title %}{{ obj.name }} sn. {{ obj.serial }} {% endblock title %}
{% block custom_page_scripts %}
<script src="{% static 'objects/objects-detail.js' %}" defer></script>
<script>
    pwd_req_url = '{% url 'objects:getpassword' 0 %}'
    csrfmiddlewaretoken = '{{ csrf_token }}'
</script>
{% endblock custom_page_scripts %}

{% block body_contents %}
    <div class="row">
        {% iloerrors obj.id %}
    </div>
    {% if obj.parentobject %}
    <div class="row">
        {% iloerrors obj.parentobject.id %}
    </div>
    {% endif %}
    <div class="row">
    <div class="panel panel-hover panel-info">
        <div class="panel-heading">
            {% fa_icon "info-circle" %} {{ obj.name }}
        </div>
        <div class="panel-body">
            {% if obj.image %}
                <div class="col-md-3">
                    <p class="text-center">
                    <img style="max-height: 150px;" src="{{ obj.image.url }}" alt="{{ obj.name }}"
                         class="img-thumbnail">
                    </p>
                </div>
            {% endif %}
            <div class="col-md-3">
                <p>
                    <strong>Seriale</strong>: {{ obj.serial }}<br />
                    <strong>Part:</strong> {{ obj.item }}<br />
                    <strong>IP:</strong> {{ obj.primary_ip }}<br />
                    <strong>Ubicazione</strong>: {{ obj.location }}<br/>
                    {% if obj.parentobject %}
                    <strong>Dipende da:</strong>
                    <a href="{% url 'objects:detail' obj.parentobject.id %}">
                        {{ obj.parentobject.name }}
                    </a>
                    {% endif %}
                </p>
            </div>
            <div class="col-md-3">
                <address>
                    <strong>
                        <a href="{% url 'customers:detail' obj.worksite.customer.id %}#worksite{{ obj.worksite.id }} ">
                        {{ obj.worksite.customer.name }}
                        </a>
                    </strong><br/>
                    {{ obj.worksite.fulltext|linebreaksbr }}
                </address>
            </div>
            <div class="col-md-3">
                <table class="table">
                {% for hwobj in obj.worksite.hardwareobjects.all %}
                <tr class='{% ifequal obj.id hwobj.id %}success{% endifequal %}'>
                    <td>
                        {% css_icon "hdd" %} <a title="{{ hwobj.location }}"
                                               href="{% url 'objects:detail' hwobj.id %}">{{ hwobj.name }}</a>
                    </td>
                    <td>
                        {{ hwobj.serial }}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">
                        Nessun hardware
                    </td>
                </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    <div class="panel-footer">
                    <a style="color:#ffffff" class="btn btn-success btn-xs ajax_get " href="{% url 'objects:addsetting' obj.id %}">
                        {% css_icon "cog" %} Aggiungi impostazione
                    </a>
                    <a style="color:#ffffff" class="btn btn-success btn-xs ajax_get " href="{% url 'objects:addpassword' obj.id %}">
                        {% css_icon "lock" %} Aggiungi password
                    </a>
                    <a style="color:#ffffff" class="btn btn-xs btn-primary " href="{% url 'admin:objects_hardwareobject_change' obj.id %}">
                        {% css_icon "pencil" %} Modifica dati
                    </a>
    </div>
    </div>
</div>

<div class="row">
    <ul class="nav nav-tabs">
        <li><a href="#panel_password" data-toggle="tab" aria-expanded="true">Password</a></li>
        <li><a href="#panel_settings" data-toggle="tab" aria-expanded="false">Impostazioni</a></li>
        <li><a href="#panel_activity" data-toggle="tab" aria-expanded="false">Attività</a></li>
        <li><a href="#panel_logs" data-toggle="tab" aria-expanded="false">Eventi e log</a></li>
        <li><a href="#panel_hardware" data-toggle="tab" aria-expanded="false">Hardware</a></li>
    </ul>
    <div class="tab-content" style="margin-top: 15px;">
        <div class="tab-pane fade" id="panel_password">
        <div class="row">
            {% regroup obj.softwarepasswords.all by settingtype.group as group_list %}
            {% for groupitem in group_list %}

                <div class="col-md-4">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                                {% css_icon "lock" %} {{ groupitem.grouper }}
                                <a class="ajax_get btn btn-xs btn-primary pull-right"
                                href="{% url 'objects:addpassword' obj.id %}?grp={{ groupitem.grouper.firstsetting.id }}">
                                    {% css_icon "plus" %}
                                </a>
                        </div>
                        <div class="panel-body">
                            {% regroup groupitem.list by settingtype as type_list %}
                            {% for setitem in type_list %}
                                <h5>
                                    {{ setitem.grouper.name }}
                                    <a class="pull-right ajax_get"
                                       href="{% url 'objects:addpassword' obj.id %}?grp={{ setitem.grouper.id }}">
                                        {% css_icon "plus-sign" %}
                                    </a>
                                </h5>
                                {% for val in setitem.list %}
                                <div>
                                    <a href="{% url 'objects:password' obj.id val.id %}" class="btn btn-xs ajax_get">
                                        {% css_icon "pencil" %}</a>
                                    {% if val.url %}
                                    <a href="{{ val.url }}" target="_blank">{% css_icon "link" %}</a>
                                    {% endif %}
                                    <strong>{{ val.username }}</strong>&nbsp;&nbsp;&nbsp;
                                    <button type="button" data-target="pwd-{{ val.id }}" data-id="{{ val.id }}"
                                            class="btn btn-warning btn-xs btn-password pull-right">
                                        {% css_icon 'eye-close' %} Vedi password
                                    </button>
                                    <div class="input-group input-sm" style="display:none;">
                                        <div class="input-group-addon">
                                            <a class="copyclipboard" href="#">
                                                {% css_icon "paperclip" %}
                                            </a>
                                        </div>
                                        <input class="form-control " style="font-family: monospace" type="text" data-viewtimeout="15" value="" id="pwd-{{ val.id }}"
                                               readonly="1">
                                        <div class="input-group-addon">...</div>
                                    </div>
                                </div>
                                {% endfor %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        </div>


        <div class="tab-pane fade" id="panel_settings">
            <div class="row">
                {% regroup obj.settings.all by type.group as setting_list %}
                {% for setitem in setting_list %}
                    <div class="col-md-4">
                        <div class="panel panel-success">
                            <div class="panel-heading">

                            {% css_icon "cog" %} {{ setitem.grouper }}
                                <a class="ajax_get btn btn-xs btn-primary pull-right"
                                      href="{% url 'objects:addsetting' obj.id %}?grp={{ setitem.grouper.firstsetting.id }}">
                                    {% css_icon "plus" %}</a>
                            </div>
                            <div class="panel-body">
                                {% for val in setitem.list %}
                                <div class="col-lg-12" style="border-bottom: 1px solid #DDDDDD">
                                    <div class="col-lg-1">
                                        <a href="{% url 'objects:setting' obj.id val.id %}"
                                          class="btn btn-xs ajax_get">
                                        {% css_icon "pencil" %}
                                        </a>&nbsp;
                                    </div>
                                    <div class="col-lg-4">
                                        <strong>{{ val.type.name }}</strong>
                                    </div>
                                    <div class="col-lg-6">
                                        {{ val.value|linebreaksbr }}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="tab-pane fade" id="panel_activity">
                <div class="" style="min-height:450px;">
                    {% toactivatetask obj %}
                    <h4 class="well well-sm">Da eseguire</h4>
                    {% include "ittasks/tasklist.html" with tasks_toread=openedtasks %}

                    <h4 class="well well-sm">Eseguite</h4>
                    {% include "ittasks/tasklist.html" with tasks_toread=closedtasks %}
                </div>

        </div>
        <div class="tab-pane fade" id="panel_logs">
                {% hwlogs obj 25 %}

        </div>
        <div class="tab-pane fade" id="panel_hardware">
            <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            Hardware Status <img class="pull-right" style="height: 22px;" src="{% static "hplogo.png" %}">
                        </div>
                        <div class="panel-body">
                            {% ilostatus obj %}
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            Strumenti
                        </div>
                        <div class="panel-body">
                            <a class="btn btn-xs btn-primary" href="{{ obj.get_upload_url }}">
                            Upload manuale...
                            </a>
                            <a class="btn btn-xs btn-primary" href="{% url 'hpilo:createpack' obj.id %}">
                            Crea pacchetto monitoraggio...
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalFormTitle">Modal title</h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>
{% endblock body_contents %}

objects/templates/objects/logs_table.html
{% load itmemory_tags %}
<div>
    {% if group_logs %}
        <div>
            <ul class="nav nav-pills" role="tablist">
                <li role="presentation" class="{% if active_filter == -1 %}active{% endif %}">
                    <a class="btn" href=".#panel_logs">Tutti</a>
                </li>
                {% for slog in group_logs %}
                <li role="presentation" class="{% if slog.active %}active{% endif %}">
                    <a class="btn" href="?filter_log={{ slog.id }}#panel_logs">{{ slog.name }} <span class="badge">{{ slog.count }}</span></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
<table class="table table-condensed">
    <thead>
    <tr>
        <th>Level</th>
        <th>Time</th>
        <th>Log</th>
        <th>Message</th>
    </tr>
    </thead>
    <tbody>
    {% for log in logs %}
    <tr>
        <td>
            {% css_icon log.level_icon %} {{ log.get_level_display }}
        </td>
        <td>
            {{ log.time }}
        </td>
        <td>
            {{ log.log_name }}
        </td>
        <td>
            <span title="{{ log.message }}">{{ log.short_message }}</span>
        </td>
    </tr>
    {% endfor %}
    </tbody>

</table>
</div>

objects/templates/objects/password.html
{% extends 'base_popup.html' %}
{% load staticfiles %}
{% load objects_tags %}
{% load itmemory_tags %}

{% block body_contents %}
<form action="{{ request.path }}" method="post">
    {% csrf_token %}
    {{ form.hardwareobject.as_hidden }}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="Salva">
</form>
<script>
    $(function() {
        $("input,select,textarea").addClass("form-control");
        $("#modalFormTitle").text("Aggiungi/Modifica");
    });

</script>
{% endblock body_contents %}