home/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from home import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
]

itmemory/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from home.views import Search

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^search', login_required(Search.as_view()), name='index'),
    url(r'^objects/', include('objects.urls', namespace="objects")),
    url(r'^ittasks/', include('ittasks.urls', namespace="ittasks")),
    url(r'^customers/', include('customers.urls', namespace="customers")),
    url(r'^hwlogs/', include('hwlogs.urls', namespace="hwlogs")),
    url(r'^hpilo/', include('hpilo.urls', namespace="hpilo")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin_tools/', include('admin_tools.urls')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns(
    'django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'login.html'}, name='mysite_login'),
    url(r'^logout/$', 'logout', {'next_page': '/'}, name='mysite_logout'),
)

ittasks/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from ittasks import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>[0-9]+)/setenable$', views.setenabledtask, name='setenabledtask'),
    url(r'^(?P<pk>[0-9]+)/updatechecks$', views.updatechecks, name='updatechecks'),
    url(r'^(?P<pk>[0-9]+)/updateuser$', views.updateuser, name='updateuser'),
    url(r'^(?P<pk>[0-9]+)/close$', views.closetask, name='closetask'),
    url(r'^calendar/(?P<month>[0-9]+)/(?P<year>[0-9]+)$', views.calendar, name='calendar'),
]

ittasks/models.py
# coding=utf-8
from datetime import datetime, timedelta
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models.query_utils import Q
from templated_email import send_templated_mail
from objects.models import HardwareObject
from dateutil.relativedelta import relativedelta
from django.db.models.signals import pre_save


class TaskTemplate(models.Model):
    class Meta():
        verbose_name = u"Modello attività"
        verbose_name_plural = u"Modelli attività"

    name = models.CharField(max_length=100, verbose_name="Nome")

    day = models.CharField(max_length=2, verbose_name="Giorni")
    month = models.CharField(max_length=2, verbose_name="Mesi")
    year = models.CharField(max_length=4, verbose_name="Anni")

    hour = models.CharField(max_length=2, verbose_name="Ore")
    minute = models.CharField(max_length=2, verbose_name="Minuti")
    enabled = models.BooleanField(default=True, verbose_name="Abilitato")

    send_reminder = models.BooleanField(default=True, verbose_name="Invia promemoria")
    send_reminder_group = models.ForeignKey(Group, null=True, blank=True,
                                            related_name="template_to_notify",
                                            verbose_name="Gruppo notifiche")

    send_expiration = models.BooleanField(default=True, verbose_name="Invia promemoria scadenza")
    send_expiration_group = models.ForeignKey(Group, null=True, blank=True,
                                              related_name="template_exp_to_notify",
                                              verbose_name="Gruppo notifiche scadenze")

    def __unicode__(self):
        return self.name


class TaskCheckTemplate(models.Model):
    class Meta():
        verbose_name = "Modello controllo"
        verbose_name_plural = "Modelli controlli"

    tasktemplate = models.ForeignKey(TaskTemplate, related_name='taskchecktemplates', verbose_name="Modello di Task")

    name = models.CharField(max_length=100, verbose_name="Nome del controllo")
    description = models.TextField(max_length=1000, verbose_name="Descrizione dell'operazione da eseguire")

    def __unicode__(self):
        return self.tasktemplate.name + " " + self.name


class Task(models.Model):
    class Meta():
        verbose_name = u"Attività"
        verbose_name_plural = u"Attività"

    template = models.ForeignKey(TaskTemplate, related_name='tasks', verbose_name="Modello di task")
    hardwareobject = models.ForeignKey(HardwareObject, related_name='tasks',
                                       verbose_name="Hardware associato")

    enabled = models.BooleanField(default=True, verbose_name="Abilitato")
    done = models.BooleanField(default=False, verbose_name="Completato")
    laststart = models.DateTimeField(null=True, blank=True, verbose_name="Ultimo avvio/esecuzione")
    user = models.ForeignKey(User, null=True, blank=True, related_name="assigned_tasks", verbose_name="Utente assegnato")
    reminder_send_date = models.DateTimeField(null=True, blank=True, verbose_name="Ultimo invio promemoria")
    expired_send_date = models.DateTimeField(null=True, blank=True, verbose_name="Ultimo invio scadenza")

    def _send_reminder(self):
        check_date = datetime.now().date()
        # print("l_date " + str(self.laststart))

        if self.done or not self.template.send_reminder:
            return False

        e_date = (self.laststart + relativedelta(days=settings.TASK_EXPIRED_DAYS)).date()

        if e_date < check_date:
            return False

        r_date = (self.laststart - relativedelta(days=settings.TASK_REMIND_DAYS)).date()
        if self.reminder_send_date is not None:
            if check_date <= self.reminder_send_date.date():
                return False
        # print("r_date " + str(r_date))
        return r_date < check_date

    def _send_expiration(self):
        check_date = datetime.now().date()
        # print("l_date " + str(self.laststart))
        if self.done or not self.template.send_expiration:
            return False
        e_date = (self.laststart + relativedelta(days=settings.TASK_EXPIRED_DAYS)).date()
        if self.expired_send_date is not None:
            if check_date <= self.expired_send_date.date():
                return False
        # print("e_date " + str(e_date))
        return e_date < check_date

    def _createnext(self):
        newtask = Task(
            template=self.template,
            hardwareobject=self.hardwareobject
        )
        newtask.enabled = True
        newtask.done = False
        newtask.laststart = self.nextstart
        newtask.save()
        return newtask

    def _nextstart(self):
        rd = relativedelta()
        tmpl = self.template
        if tmpl.day != '*':
            rd += relativedelta(days=int(tmpl.day))
        if tmpl.month != '*':
            rd += relativedelta(months=int(tmpl.month))
        if tmpl.year != '*':
            rd += relativedelta(years=int(tmpl.year))
        if tmpl.hour != '*':
            rd += relativedelta(hours=int(tmpl.hour))
        if tmpl.minute != '*':
            rd += relativedelta(minutes=int(tmpl.minute))
        return self.laststart + rd

    def _to_past(self):
        return (self.laststart < datetime.now()) and not self.done

    def _updatechecks(self):
        chkstmpl = TaskCheckTemplate.objects.filter(tasktemplate_id=self.template_id)
        for checktmpl in chkstmpl:
            if not TaskCheck.objects.filter(task_id=self.id, checktemplate_id=checktmpl.id):
                ntaskcheck = TaskCheck(task=self, checktemplate=checktmpl)
                ntaskcheck.exectime = datetime.now()
                ntaskcheck.save()
        return chkstmpl

    to_past = property(_to_past)
    nextstart = property(_nextstart)
    createnext = property(_createnext)
    updatechecks = property(_updatechecks)
    send_reminder = property(_send_reminder)
    send_expiration = property(_send_expiration)

    def _progress(self):
        ok = self.tasks.exclude(result=0).count()
        total = self.tasks.count()
        return int((float(ok) / float(total)) * 100)

    progress = property(_progress)

    def has_changed(self, field):
        if not self.pk:
            return False
        old_value = self.__class__._default_manager.filter(pk=self.pk).values(field).get()[field]
        value = getattr(self, field)
        if value is not None:
            value = value.id
        return not value == old_value

    def get_original(self, field):
        if not self.pk:
            return getattr(instance, field)
        old_value = self.__class__._default_manager.filter(pk=self.pk).values(field).get()[field]
        return old_value

    def __unicode__(self):
        return self.hardwareobject.name + " -> " + self.template.name


class TaskCheck(models.Model):
    class Meta():
        verbose_name = "Controllo"
        verbose_name_plural = "Controlli"

    task = models.ForeignKey(Task, related_name='tasks', verbose_name="Task")
    checktemplate = models.ForeignKey(TaskCheckTemplate, related_name='checktemplates', verbose_name="Modello di task")

    exectime = models.DateTimeField(verbose_name="Data di esecuzione")
    RESULT_VALUES = (
        (0, 'Non eseguito (NE)'),
        (1, 'Passato (PASS)'),
        (4, 'Passato con errori (WARN)'),
        (2, 'Fallito (NG)'),
        (3, 'Non applicabile (NA)'),
    )
    RESULT_VALUES_CLASS = {
        0: 'warning',
        1: 'primary',
        2: 'danger',
        3: 'info',
        4: 'warning',
    }
    result = models.IntegerField(default=0,
                                 choices=RESULT_VALUES,
                                 verbose_name="Risultato")

    def _cssresult(self):
        return self.RESULT_VALUES_CLASS[int(self.result)]

    cssresult = property(_cssresult)
    note = models.TextField(max_length=1000, null=True, blank=True, verbose_name="Note sul controllo")

    def __unicode__(self):
        return unicode(self.task) + " " + self.checktemplate.name + " " + (self.get_result_display())


def send_mail_user(task, user, template):
    if user.email is None:
        return
    return send_templated_mail(
        template_name=template,
        from_email=settings.EMAIL_SENDER,
        recipient_list=[user.email],
        context={
            'username': user.username,
            'full_name': user.get_full_name(),
            'task': task
        },
    )


def pre_save_task(sender, **kwargs):
    task = kwargs['instance']
    if task.has_changed('user'):
        origuserid = task.get_original('user')
        print "Task change from {0} to {1} ".format(task.get_original('user'), task.user)
        if task.user is not None:
            try:
                send_mail_user(task, task.user, "assign_task")
            except ValueError:
                print ValueError.message
            print("Assign task: send mail to user: {0} ({1})".format(
                task.user,
                task.user.email
            ))
        if origuserid is not None:
            old_tasks = Task.objects.filter(user_id=origuserid)
            if old_tasks.count > 0:
                old_task = old_tasks[0]
                print("Assign task: send cancellation mail to user: {0} ({1})".format(
                    old_task.user,
                    old_task.user.email
                ))
                try:
                    send_mail_user(old_task, old_task.user, "cancel_task")
                except ValueError:
                    print ValueError.message

pre_save.connect(pre_save_task, sender=Task)

ittasks/views.py
# coding=utf-8
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils.datetime_safe import datetime
from django.views import generic
from django.forms.models import modelformset_factory
from ittasks.models import Task
from ittasks.models import TaskCheck, TaskCheckTemplate
from django.contrib.auth.models import User
from django.forms import HiddenInput, Textarea, RadioSelect
from lib.booleanyesno import HorizRadioRenderer


def updatechecks(request, pk):
    if request.user.is_authenticated() and request.is_ajax:
        tsk = get_object_or_404(Task, id=pk)
        tsk.updatechecks
        return HttpResponseRedirect(reverse('ittasks:detail', args=(tsk.id,)))
    else:
        return HttpResponse("invalid data or error")


def closetask(request, pk):
    if request.user.is_authenticated() and request.is_ajax:
        tsk = get_object_or_404(Task, id=pk)
        tsk.laststart = datetime.now()
        tsk.done = True
        tsk.save()
        if tsk.enabled:
            newtask = tsk.createnext
            newtask.updatechecks
        return JsonResponse({"redirect": reverse('ittasks:detail', args=(tsk.id,))})
    else:
        return HttpResponse("invalid data or error")


def updateuser(request, pk):
    if request.user.is_authenticated() and request.POST and request.is_ajax:
        tsk = get_object_or_404(Task, id=pk)
        if request.POST['new_user'].isdigit():
            tsk.user = User.objects.get(id=request.POST['new_user'])
        else:
            tsk.user = None
        tsk.save()
        return JsonResponse({"success": True})
    else:
        return HttpResponse("invalid data or error")


def setenabledtask(request, pk):
    if request.user.is_authenticated() and request.is_ajax:
        tsk = get_object_or_404(Task, id=pk)
        tsk.enabled = not tsk.enabled
        tsk.save()
        return JsonResponse({"enabled": tsk.enabled})
    else:
        return HttpResponse("invalid data or error")


def calendar(request, month, year):
    if request.user.is_authenticated() :
        return TemplateResponse(request,"ajax_calendar.html",{'month':month,'year': year})
    else:
        return HttpResponse("invalid data or error")


class IndexView(generic.TemplateView):
    # TODO: Da inserire lista attività e gestione
    template_name = 'ittasks/index.html'


class DetailView(generic.DetailView):
    model = Task
    template_name = 'ittasks/detail.html'
    context_object_name = 'obj'

    def post(self, request, *args, **kwargs):
        taskcheckform = modelformset_factory(TaskCheck)
        frm = taskcheckform(request.POST)
        if frm.is_valid:
            frm.save()
        # import pdb
        # pdb.set_trace()
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)

        checkslist = TaskCheck.objects.filter(task_id=context['obj'].id)
        wdg = {
            'note': Textarea(attrs={'rows': 2, 'cols': 22}),
            'task': HiddenInput,
            'exectime': HiddenInput,
            'checktemplate': HiddenInput,
        }

        taskcheckuser = modelformset_factory(Task, fields=['id', 'user'], can_delete=False, extra=0)
        taskcheckuserform = taskcheckuser(queryset=Task.objects.filter(id=context['obj'].id))
        # import pdb
        #pdb.set_trace()
        context['formsetuser'] = taskcheckuserform
        taskcheckform = modelformset_factory(TaskCheck, widgets=wdg, can_delete=False, extra=0)
        context['formset'] = taskcheckform(queryset=checkslist)
        context['checkstatuscss'] = {
            0: 'warning',
            1: 'info',
            2: 'danger'
        }
        return context

    def get_queryset(self):
        return Task.objects.all()

ittasks/templates/ittasks/detail.html
{% extends 'objects/index.html' %}

{% load itmemory_tags %}
{% load sbadmin_tags %}
{% load staticfiles %}

{% block body_contents %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            {% fa_icon "info-circle" %} {{ obj.template.name }}
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    {% if obj.hardwareobject.image %}
                    <p class="text-center">
                    <img style="max-height: 100px;max-width: 220px; margin-right:22px;" src="{{ obj.hardwareobject.image.url }}" alt="{{ obj.hardwareobject.name }}" class="img-thumbnail pull-left">
                    </p>
                    {% endif %}
                    <p>
                        {{ obj.hardwareobject.name }}
                         <a class="btn btn-xs btn-primary pull-right"
                           href="{% url 'objects:detail' obj.hardwareobject.id %}">
                            {% css_icon 'search' %}
                         </a>
                    </p>
                    <p>{{ obj.hardwareobject.worksite.customer.name }}
                        <a class="btn btn-xs btn-primary pull-right"
                           href="{% url 'customers:detail' obj.hardwareobject.worksite.customer.id %}">
                            {% css_icon 'search' %}
                        </a>
                    </p>
                    <p>{{ obj.hardwareobject.worksite.name }}
                        <a class="btn btn-xs btn-primary pull-right"
                           href="{% url 'customers:detail' obj.hardwareobject.worksite.customer.id %}#worksite{{ obj.hardwareobject.worksite.id }} ">
                            {% css_icon 'search' %}
                        </a>

                    </p>
                </div>
                <div class="col-md-6">
        <p>
            Esecuzione: {{ obj.laststart }} {% if not obj.done %}
            (<span id="taskstatus">{{ obj.enabled|yesno:"abilitato,disabilitato,mai" }}</span>)
            <button style="width:65px;" class="btn btn-info btn-xs" id="enabletask" class="button">
                {{ obj.enabled|yesno:"disabilita,abilita,mai" }}
            </button>
            {% endif %}
        </p>
        <p>Completato: {{ obj.done|yesno:"si,no,mai" }}</p>
        {% if not obj.done %}
        <p>Prossima: {{ obj.nextstart }}</p>
        {% for formuser in formsetuser %}
        <p>Utente assegnato: {{ formuser.user }}</p>
        {% endfor %}
        {% else %}
        <p>Operatore: {{ obj.user.get_full_name }}</p>
        {% endif %}

                </div>
            </div>

        </div>
        {% if not obj.done %}
        <div class="panel-footer text-right">
            <a class="btn btn-info" href="{% url 'ittasks:updatechecks' obj.id %}">{% css_icon "refresh" %} Aggiorna i controlli</a>
            <button id="closebtn2" class="btn btn-primary">Completa e chiudi</button>
        </div>
        {% endif %}

    </div>
</div>
<div class="row">
    <div class="panel panel-info">
    <div class="panel-heading">
        {% if not obj.done %}
            Controlli da eseguire
        {% else %}
            Controlli eseguiti
        {% endif %}
    </div>
    <div class="panel-body">
        <form method="post" action="">
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="table table-bordered">
                <tr>
                    <th>Nome</th>
                    <th>Data esecuzione</th>
                    <th>Esito</th>
                    <th colspan="2">Annotazioni</th>
                </tr>
                {% for form in formset %}
                <tr>
                    <td>
                        <dl>
                            <dt>{{ form.instance.checktemplate.name }}</dt>
                            <dd>{{ form.instance.checktemplate.description }}</dd>
                        </dl>
                    </td>
                    <td>
                        {{ form.instance.exectime }}
                        {{ form.id }}
                        {{ form.task }}
                        {{ form.checktemplate }}
                        {{ form.exectime }}
                    </td>
                    {% if not obj.done %}
                    <td>
                        {{ form.result }}
                    </td>
                    <td>
                        {{ form.note }}
                    </td>
                    <td style="text-align:center;vertical-align: middle;">
                        <input class="btn btn-primary" type="submit" value="Salva"/>
                    </td>
                    {% else %}
                    <td>
                        <p class="bg-{{ form.instance.cssresult }}">{{ form.instance.get_result_display }}</p>
                    </td>
                    <td colspan="2">
                        {{ form.instance.note }}
                    </td>
                    {% endif %}
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">Nessun controllo visibile prova ad aggiornare la lista dei controlli</td>
                </tr>
                {% endfor %}

            </table>
        </form>
    </div>
        {% if not obj.done %}
        <div class="panel-footer text-right">
            <a class="btn btn-info" href="{% url 'ittasks:updatechecks' obj.id %}">{% css_icon "refresh" %} Aggiorna i controlli</a>
            <button id="closebtn" class="btn btn-primary">Completa e chiudi</button>
        </div>
        {% endif %}
</div>
    </div>

<script>
                chusricon = null;
                $(document).ready(function() {
                    addenabledfunc($("#enabletask"))
                    addclosefunc($("#closebtn"))
                    addclosefunc($("#closebtn2"))
                    addchangeuserfunc($("#id_form-0-user"))

                    $("[id^=id_form-][id$=-result]").change(
                        function() {
                            $(this).after("<img src='{% static "img/ldr.gif" %}' />")
                            $("form").submit()
                        })

                });
                function addchangeuserfunc(ctl) {
                    ctl.after('&nbsp;&nbsp;{% css_icon 'ok' %}');
                    ctl.change(function(event) {
                        chusricon = $(this).next().removeClass("glyphicon-ok").addClass("glyphicon-transfer");
                        $.post(
                            '{% url 'ittasks:updateuser' obj.id %}',
                             { 'csrfmiddlewaretoken': '{{ csrf_token }}' ,'new_user': this.value},
                             function(data) {
                                if (data.success) {
                                    window.setTimeout(function() {
                                        chusricon.removeClass("glyphicon-transfer").addClass("glyphicon-ok");
                                    }, 1000);
                                } else {
                                    alert("aggiornamento non riuscito, provare a ricaricare la pagina")
                                }
                             }
                        );
                        event.preventDefault()
                    });
                }
                function addenabledfunc(ctl) {
                    ctl.click(function(event) {
                        $.getJSON(
                            '{% url 'ittasks:setenabledtask' obj.id %}',
                             function(data) {
                                $("#enabletask").text(data.enabled?"disabilita":"abilita");
                                $("#taskstatus").text(data.enabled?"abilitato":"disabilitato");
                                $("#enabletask").removeClass("btn-info").addClass("btn-success");
                                window.setTimeout(function() {
                                    $("#enabletask").removeClass("btn-success").addClass("btn-info");
                                }, 1500);

                             }
                        );
                        event.preventDefault()
                    });
                }
                function addclosefunc(ctl) {
                    ctl.click(function(event) {
                        $.getJSON(
                            '{% url 'ittasks:closetask' obj.id %}',
                             function(data) {
                                document.location.href = data.redirect
                             }
                        );
                        event.preventDefault()
                    });
                }


</script>

{% endblock body_contents %}

ittasks/templates/ittasks/index.html
{% extends 'base.html' %}
{% load tasks_calendar %}
{% block title %}Attività{% endblock title %}
{% block body_contents %}

<div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Calendario</h1>
            {% taskcalendar %}
            {% ctl_calendar %}
        </div>
</div>

{% endblock %}

ittasks/templates/ittasks/tasklist.html
{% load humanize %}
{% load itmemory_tags %}
    {% for taskop in tasks_toread %}
<p style="border-bottom: solid 1px #DDDDDD; padding-bottom: 2px;padding-top: 2px; margin-bottom: 5px;">
    {% if taskop.to_past %}
    {% css_icon 'fire' %}
    {% endif %}
    <a class="btn btn-xs btn-info" href="{% url 'ittasks:detail' taskop.id %}">{{ taskop.template.name|truncatechars:20 }}</a>
    <small class="text-muted pull-right">
        <span title="{{ taskop.laststart }}">
            &nbsp;{% css_icon 'calendar' %} {{ taskop.laststart|naturaltime }}
        </span>
    </small>
    <br/>
    {% if taskop.user %}
    <span title="{{ taskop.hardwareobject.worksite }}" >
        <strong>
        {{ taskop.hardwareobject.worksite|truncatechars:22 }}
        </strong>
    </span>
    &nbsp;
    <span title="{{ taskop.hardwareobject.name }}">
        {{ taskop.hardwareobject.name|truncatechars:13 }}
    </span>
    <small class="text-muted pull-right">
        &nbsp;{% css_icon 'user' %} {{ taskop.user }}
    </small>
    {% else %}
    <span title="{{ taskop.hardwareobject.worksite }}" >
        <strong>
        {{ taskop.hardwareobject.worksite|truncatechars:33 }}
        </strong>
    </span>
    &nbsp;
    <span title="{{ taskop.hardwareobject.name }}">
        {{ taskop.hardwareobject.name|truncatechars:22 }}
    </span>
    {% endif %}
</p>
    {% endfor %}
<p>&nbsp;</p>