home/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from home import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
]

itmemory/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from home.views import Search

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^search', login_required(Search.as_view()), name='index'),
    url(r'^objects/', include('objects.urls', namespace="objects")),
    url(r'^ittasks/', include('ittasks.urls', namespace="ittasks")),
    url(r'^customers/', include('customers.urls', namespace="customers")),
    url(r'^hwlogs/', include('hwlogs.urls', namespace="hwlogs")),
    url(r'^hpilo/', include('hpilo.urls', namespace="hpilo")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin_tools/', include('admin_tools.urls')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns(
    'django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'login.html'}, name='mysite_login'),
    url(r'^logout/$', 'logout', {'next_page': '/'}, name='mysite_logout'),
)

ittasks/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from ittasks import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>[0-9]+)/setenable$', views.setenabledtask, name='setenabledtask'),
    url(r'^(?P<pk>[0-9]+)/updatechecks$', views.updatechecks, name='updatechecks'),
    url(r'^(?P<pk>[0-9]+)/updateuser$', views.updateuser, name='updateuser'),
    url(r'^(?P<pk>[0-9]+)/close$', views.closetask, name='closetask'),
    url(r'^calendar/(?P<month>[0-9]+)/(?P<year>[0-9]+)$', views.calendar, name='calendar'),
]

ittasks/models.py
# coding=utf-8
from datetime import datetime, timedelta
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models.query_utils import Q
from templated_email import send_templated_mail
from objects.models import HardwareObject
from dateutil.relativedelta import relativedelta
from django.db.models.signals import pre_save


class TaskTemplate(models.Model):
    class Meta():
        verbose_name = u"Modello attività"
        verbose_name_plural = u"Modelli attività"

    name = models.CharField(max_length=100, verbose_name="Nome")

    day = models.CharField(max_length=2, verbose_name="Giorni")
    month = models.CharField(max_length=2, verbose_name="Mesi")
    year = models.CharField(max_length=4, verbose_name="Anni")

    hour = models.CharField(max_length=2, verbose_name="Ore")
    minute = models.CharField(max_length=2, verbose_name="Minuti")
    enabled = models.BooleanField(default=True, verbose_name="Abilitato")

    send_reminder = models.BooleanField(default=True, verbose_name="Invia promemoria")
    send_reminder_group = models.ForeignKey(Group, null=True, blank=True,
                                            related_name="template_to_notify",
                                            verbose_name="Gruppo notifiche")

    send_expiration = models.BooleanField(default=True, verbose_name="Invia promemoria scadenza")
    send_expiration_group = models.ForeignKey(Group, null=True, blank=True,
                                              related_name="template_exp_to_notify",
                                              verbose_name="Gruppo notifiche scadenze")

    def __unicode__(self):
        return self.name


class TaskCheckTemplate(models.Model):
    class Meta():
        verbose_name = "Modello controllo"
        verbose_name_plural = "Modelli controlli"

    tasktemplate = models.ForeignKey(TaskTemplate, related_name='taskchecktemplates', verbose_name="Modello di Task")

    name = models.CharField(max_length=100, verbose_name="Nome del controllo")
    description = models.TextField(max_length=1000, verbose_name="Descrizione dell'operazione da eseguire")

    def __unicode__(self):
        return self.tasktemplate.name + " " + self.name


class Task(models.Model):
    class Meta():
        verbose_name = u"Attività"
        verbose_name_plural = u"Attività"

    template = models.ForeignKey(TaskTemplate, related_name='tasks', verbose_name="Modello di task")
    hardwareobject = models.ForeignKey(HardwareObject, related_name='tasks',
                                       verbose_name="Hardware associato")

    enabled = models.BooleanField(default=True, verbose_name="Abilitato")
    done = models.BooleanField(default=False, verbose_name="Completato")
    laststart = models.DateTimeField(null=True, blank=True, verbose_name="Ultimo avvio/esecuzione")
    user = models.ForeignKey(User, null=True, blank=True, related_name="assigned_tasks", verbose_name="Utente assegnato")
    reminder_send_date = models.DateTimeField(null=True, blank=True, verbose_name="Ultimo invio promemoria")
    expired_send_date = models.DateTimeField(null=True, blank=True, verbose_name="Ultimo invio scadenza")

    def _send_reminder(self):
        check_date = datetime.now().date()
        # print("l_date " + str(self.laststart))

        if self.done or not self.template.send_reminder:
            return False

        e_date = (self.laststart + relativedelta(days=settings.TASK_EXPIRED_DAYS)).date()

        if e_date < check_date:
            return False

        r_date = (self.laststart - relativedelta(days=settings.TASK_REMIND_DAYS)).date()
        if self.reminder_send_date is not None:
            if check_date <= self.reminder_send_date.date():
                return False
        # print("r_date " + str(r_date))
        return r_date < check_date

    def _send_expiration(self):
        check_date = datetime.now().date()
        # print("l_date " + str(self.laststart))
        if self.done or not self.template.send_expiration:
            return False
        e_date = (self.laststart + relativedelta(days=settings.TASK_EXPIRED_DAYS)).date()
        if self.expired_send_date is not None:
            if check_date <= self.expired_send_date.date():
                return False
        # print("e_date " + str(e_date))
        return e_date < check_date

    def _createnext(self):
        newtask = Task(
            template=self.template,
            hardwareobject=self.hardwareobject
        )
        newtask.enabled = True
        newtask.done = False
        newtask.laststart = self.nextstart
        newtask.save()
        return newtask

    def _nextstart(self):
        rd = relativedelta()
        tmpl = self.template
        if tmpl.day != '*':
            rd += relativedelta(days=int(tmpl.day))
        if tmpl.month != '*':
            rd += relativedelta(months=int(tmpl.month))
        if tmpl.year != '*':
            rd += relativedelta(years=int(tmpl.year))
        if tmpl.hour != '*':
            rd += relativedelta(hours=int(tmpl.hour))
        if tmpl.minute != '*':
            rd += relativedelta(minutes=int(tmpl.minute))
        return self.laststart + rd

    def _to_past(self):
        return (self.laststart < datetime.now()) and not self.done

    def _updatechecks(self):
        chkstmpl = TaskCheckTemplate.objects.filter(tasktemplate_id=self.template_id)
        for checktmpl in chkstmpl:
            if not TaskCheck.objects.filter(task_id=self.id, checktemplate_id=checktmpl.id):
                ntaskcheck = TaskCheck(task=self, checktemplate=checktmpl)
                ntaskcheck.exectime = datetime.now()
                ntaskcheck.save()
        return chkstmpl

    to_past = property(_to_past)
    nextstart = property(_nextstart)
    createnext = property(_createnext)
    updatechecks = property(_updatechecks)
    send_reminder = property(_send_reminder)
    send_expiration = property(_send_expiration)

    def _progress(self):
        ok = self.tasks.exclude(result=0).count()
        total = self.tasks.count()
        return int((float(ok) / float(total)) * 100)

    progress = property(_progress)

    def has_changed(self, field):
        if not self.pk:
            return False
        old_value = self.__class__._default_manager.filter(pk=self.pk).values(field).get()[field]
        value = getattr(self, field)
        if value is not None:
            value = value.id
        return not value == old_value

    def get_original(self, field):
        if not self.pk:
            return getattr(instance, field)
        old_value = self.__class__._default_manager.filter(pk=self.pk).values(field).get()[field]
        return old_value

    def __unicode__(self):
        return self.hardwareobject.name + " -> " + self.template.name


class TaskCheck(models.Model):
    class Meta():
        verbose_name = "Controllo"
        verbose_name_plural = "Controlli"

    task = models.ForeignKey(Task, related_name='tasks', verbose_name="Task")
    checktemplate = models.ForeignKey(TaskCheckTemplate, related_name='checktemplates', verbose_name="Modello di task")

    exectime = models.DateTimeField(verbose_name="Data di esecuzione")
    RESULT_VALUES = (
        (0, 'Non eseguito (NE)'),
        (1, 'Passato (PASS)'),
        (4, 'Passato con errori (WARN)'),
        (2, 'Fallito (NG)'),
        (3, 'Non applicabile (NA)'),
    )
    RESULT_VALUES_CLASS = {
        0: 'warning',
        1: 'primary',
        2: 'danger',
        3: 'info',
        4: 'warning',
    }
    result = models.IntegerField(default=0,
                                 choices=RESULT_VALUES,
                                 verbose_name="Risultato")

    def _cssresult(self):
        return self.RESULT_VALUES_CLASS[int(self.result)]

    cssresult = property(_cssresult)
    note = models.TextField(max_length=1000, null=True, blank=True, verbose_name="Note sul controllo")

    def __unicode__(self):
        return unicode(self.task) + " " + self.checktemplate.name + " " + (self.get_result_display())


def send_mail_user(task, user, template):
    if user.email is None:
        return
    return send_templated_mail(
        template_name=template,
        from_email=settings.EMAIL_SENDER,
        recipient_list=[user.email],
        context={
            'username': user.username,
            'full_name': user.get_full_name(),
            'task': task
        },
    )


def pre_save_task(sender, **kwargs):
    task = kwargs['instance']
    if task.has_changed('user'):
        origuserid = task.get_original('user')
        print "Task change from {0} to {1} ".format(task.get_original('user'), task.user)
        if task.user is not None:
            try:
                send_mail_user(task, task.user, "assign_task")
            except ValueError:
                print ValueError.message
            print("Assign task: send mail to user: {0} ({1})".format(
                task.user,
                task.user.email
            ))
        if origuserid is not None:
            old_tasks = Task.objects.filter(user_id=origuserid)
            if old_tasks.count > 0:
                old_task = old_tasks[0]
                print("Assign task: send cancellation mail to user: {0} ({1})".format(
                    old_task.user,
                    old_task.user.email
                ))
                try:
                    send_mail_user(old_task, old_task.user, "cancel_task")
                except ValueError:
                    print ValueError.message

pre_save.connect(pre_save_task, sender=Task)

ittasks/views.py
# coding=utf-8
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils.datetime_safe import datetime
from django.views import generic
from django.forms.models import modelformset_factory
from ittasks.models import Task
from ittasks.models import TaskCheck, TaskCheckTemplate
from django.contrib.auth.models import User
from django.forms import HiddenInput, Textarea, RadioSelect
from lib.booleanyesno import HorizRadioRenderer


def updatechecks(request, pk):
    if request.user.is_authenticated() and request.is_ajax:
        tsk = get_object_or_404(Task, id=pk)
        tsk.updatechecks
        return HttpResponseRedirect(reverse('ittasks:detail', args=(tsk.id,)))
    else:
        return HttpResponse("invalid data or error")


def closetask(request, pk):
    if request.user.is_authenticated() and request.is_ajax:
        tsk = get_object_or_404(Task, id=pk)
        tsk.laststart = datetime.now()
        tsk.done = True
        tsk.save()
        if tsk.enabled:
            newtask = tsk.createnext
            newtask.updatechecks
        return JsonResponse({"redirect": reverse('ittasks:detail', args=(tsk.id,))})
    else:
        return HttpResponse("invalid data or error")


def updateuser(request, pk):
    if request.user.is_authenticated() and request.POST and request.is_ajax:
        tsk = get_object_or_404(Task, id=pk)
        if request.POST['new_user'].isdigit():
            tsk.user = User.objects.get(id=request.POST['new_user'])
        else:
            tsk.user = None
        tsk.save()
        return JsonResponse({"success": True})
    else:
        return HttpResponse("invalid data or error")


def setenabledtask(request, pk):
    if request.user.is_authenticated() and request.is_ajax:
        tsk = get_object_or_404(Task, id=pk)
        tsk.enabled = not tsk.enabled
        tsk.save()
        return JsonResponse({"enabled": tsk.enabled})
    else:
        return HttpResponse("invalid data or error")


def calendar(request, month, year):
    if request.user.is_authenticated() :
        return TemplateResponse(request,"ajax_calendar.html",{'month':month,'year': year})
    else:
        return HttpResponse("invalid data or error")


class IndexView(generic.TemplateView):
    # TODO: Da inserire lista attività e gestione
    template_name = 'ittasks/index.html'


class DetailView(generic.DetailView):
    model = Task
    template_name = 'ittasks/detail.html'
    context_object_name = 'obj'

    def post(self, request, *args, **kwargs):
        taskcheckform = modelformset_factory(TaskCheck)
        frm = taskcheckform(request.POST)
        if frm.is_valid:
            frm.save()
        # import pdb
        # pdb.set_trace()
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)

        checkslist = TaskCheck.objects.filter(task_id=context['obj'].id)
        wdg = {
            'note': Textarea(attrs={'rows': 2, 'cols': 22}),
            'task': HiddenInput,
            'exectime': HiddenInput,
            'checktemplate': HiddenInput,
        }

        taskcheckuser = modelformset_factory(Task, fields=['id', 'user'], can_delete=False, extra=0)
        taskcheckuserform = taskcheckuser(queryset=Task.objects.filter(id=context['obj'].id))
        # import pdb
        #pdb.set_trace()
        context['formsetuser'] = taskcheckuserform
        taskcheckform = modelformset_factory(TaskCheck, widgets=wdg, can_delete=False, extra=0)
        context['formset'] = taskcheckform(queryset=checkslist)
        context['checkstatuscss'] = {
            0: 'warning',
            1: 'info',
            2: 'danger'
        }
        return context

    def get_queryset(self):
        return Task.objects.all()

ittasks/templates/ajax_calendar.html
{% load tasks_calendar %}
{% taskcalendar month year %}

ittasks/templates/calendar.html
{% load itmemory_tags %}
<div id="calendar">
    <table class="table table-bordered" cellpadding="0" cellspacing="0">
        <thead>
        <tr>
            <td colspan="1">
                <a class="pull-left ajax_calendar" href="javascript:void(0)"
                   onclick="$('#calendar').load('{% url 'ittasks:calendar' start_day.month start_day.year %}')"
                   >{% css_icon "chevron-left" %}
                </a>
            </td>
            <td colspan="5" class="text-center">
                {{ month_name }}
            </td>
            <td colspan="1">
                <a class="pull-right ajax_calendar" href="javascript:void(0)"
                   onclick="javascript:$('#calendar').load('{% url 'ittasks:calendar' end_day.month end_day.year %}')"
                   >
                    {% css_icon "chevron-right" %}
                </a>
            </td>
        </tr>
        <tr>
            <th width="15%">Lun</th>
            <th width="14%">Mar</th>
            <th width="14%">Mer</th>
            <th width="14%">Gio</th>
            <th width="14%">Ven</th>
            <th width="14%">Sab</th>
            <th width="15%">Dom</th>
        </tr>
        </thead>
        <tbody>
            {% for day in dates %}
            {% if day.date.weekday == 0 %}<tr class="calendar_week">{% endif %}
            <td class="calendar_day{% if day.overmonth %} overmonth{% endif %}{% if day.date == now.date %} calendar_now{% endif %}">
                {% if day.events %}
                <div class="cal_w_task"></div>
                <div class="day">
                    <a href="javascript:false" role="button" data-toggle="popover" data-trigger="focus" title="Eventi">{{ day.date.day }}</a>
                </div>
                {% else %}
                <div class="day">
                    {{ day.date.day }}
                </div>
                {% endif %}
                <div style="display: none">
                    {% for task in day.events %}
                    <p class="info">
                        {% if task.done %}{% css_icon "ok" %}{% endif %}
                        <a href="{% url 'ittasks:detail' task.id %}">
                        {{ task }}
                        </a>
                    </p>
                    {% endfor %}
                </div>
            </td>
            {% if day.date.weekday == 6 %}</tr>{% endif %}
            {% endfor %}
        <tr>
            <td colspan="1">
                <a class="pull-left ajax_calendar" href="javascript:void(0)"
                   onclick="$('#calendar').load('{% url 'ittasks:calendar' start_day.month start_day.year %}')"
                   >{% css_icon "chevron-left" %}
                </a>
            </td>
            <td colspan="5" class="text-center">
                {{ month_name }}
            </td>
            <td colspan="1">
                <a class="pull-right ajax_calendar" href="javascript:void(0)"
                   onclick="javascript:$('#calendar').load('{% url 'ittasks:calendar' end_day.month end_day.year %}')"
                   >
                    {% css_icon "chevron-right" %}
                </a>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<script language="JavaScript">
    if (typeof loadpopover == 'function'){
      loadpopover()
    }
</script>

ittasks/templates/ctl_calendar.html
<script>
    function loadpopover() {
        $(function () {
            $('[data-toggle="popover"]').popover({
                html: true,
                content: function(){
                    return $(this).parent().next().html()
                }
            });
        })
    }
    window.onload = function(){loadpopover();  }
</script>

ittasks/templates/personal_task.html
<!-- tasks -->
{% for task in user_tasks %}
<li>
    <a href="/ittasks/{{ task.id }}">
        <div>
            <div>
                <strong title="{{ task.hardwareobject }}">{{ task.template.name }}</strong>
                <span class="pull-right text-muted">{{ task.progress }}%</span><br/>
                <span class="text-muted" style="font-size: 60%">{{ task.hardwareobject }}</span>
            </div>
            <div class="progress progress-striped active">
                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{ task.progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ task.progress }}%">
                    <span class="sr-only">{{ task.progress }}% Complete (success)</span>
                </div>
            </div>
        </div>
    </a>
</li>

    {% if not forloop.last %}
<li class="divider"></li>
    {% endif %}
{% endfor %}
<!-- /tasks -->